# configure updates globally
# default: all
# allowed: all, insecure, False
Update: all

# search for requirement files
# default: True
# allowed: True, False
Search: True

# configure updates globally
# default: all
# allowed: all, insecure, False
Pin: True

# set the default branch
# default: empty, the default branch on GitHub
Default Branch: master

# configure the branch prefix the bot is using
# default: pyup-
Branch pre-fix: pyup-

# allow to close stale PRs
# default: True
Close PRs: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
Label PRs: False


Update hashes: True